steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg=NEXT_PUBLIC_SUPABASE_URL",
        "--build-arg=NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY",
        "-t",
        "us-west2-docker.pkg.dev/predictpuck/predictpuck/updated_env",
        ".",
      ]
    secretEnv:
      ["NEXT_PUBLIC_SUPABASE_URL", "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY"]

images:
  - "us-west2-docker.pkg.dev/predictpuck/predictpuck/updated_env"

availableSecrets:
  secretManager:
    - versionName: projects/predictpuck/secrets/SUPABASE_URL/versions/latest
      env: NEXT_PUBLIC_SUPABASE_URL

    - versionName: projects/predictpuck/secrets/SUPABASE_KEY/versions/latest
      env: NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
